-- ============================================
-- ADD ad_student_details TABLE TO SCHEMA
-- Migration to add the student details table
-- ============================================

USE placement_portal_v2;

-- Create ad_student_details table if it doesn't exist
CREATE TABLE IF NOT EXISTS `ad_student_details` (
  `SL_NO` int(11) NOT NULL AUTO_INCREMENT,
  `enquiry_no` int(11) NOT NULL,
  `aadhar` varchar(20) DEFAULT NULL,
  `pre_adm_date` date DEFAULT NULL,
  `college` varchar(20) NOT NULL,
  `school` varchar(20) DEFAULT NULL,
  `academic_year` char(7) NOT NULL,
  `student_id` varchar(30) NOT NULL,
  `usn` varchar(30) NOT NULL,
  `name` varchar(100) NOT NULL,
  `father_name` varchar(100) NOT NULL,
  `mother_name` varchar(100) NOT NULL,
  `parent_mobile` varchar(15) NOT NULL,
  `student_mobile` varchar(20) NOT NULL,
  `regular_lateral` varchar(20) NOT NULL,
  `programme` varchar(10) NOT NULL,
  `course` varchar(30) NOT NULL,
  `discipline` varchar(50) NOT NULL,
  `admission_quota` varchar(50) NOT NULL,
  `paid_at_cet` decimal(10,2) NOT NULL,
  `cet_tat_no` varchar(20) DEFAULT NULL,
  `cet_adm` varchar(20) DEFAULT NULL,
  `allotment_date` date DEFAULT NULL,
  `round` int(11) DEFAULT NULL,
  `rank` varchar(20) DEFAULT NULL,
  `doa` date DEFAULT NULL,
  `claimed_cat` varchar(20) DEFAULT NULL,
  `alloted_cat` varchar(20) DEFAULT NULL,
  `non_karnataka` varchar(10) NOT NULL,
  `studied_gmit` varchar(10) NOT NULL,
  `gender` char(1) NOT NULL,
  `dob` date NOT NULL,
  `religion` varchar(20) NOT NULL,
  `category` varchar(20) NOT NULL,
  `caste` varchar(100) NOT NULL,
  `total_marks_puc` int(11) DEFAULT NULL,
  `marks_obtained` int(11) DEFAULT NULL,
  `puc_percentage` decimal(10,2) DEFAULT NULL,
  `pcm_total` int(11) DEFAULT NULL,
  `pcm_percentage` decimal(10,2) DEFAULT NULL,
  `cet_comedk_fees` decimal(10,2) DEFAULT NULL,
  `previous_qualification` varchar(20) DEFAULT NULL,
  `year_of_passing` varchar(10) DEFAULT NULL,
  `exam_board` varchar(200) DEFAULT NULL,
  `puc_reg_no` varchar(20) DEFAULT NULL,
  `sslc_marks` int(11) DEFAULT NULL,
  `sslc_percentage` decimal(10,2) DEFAULT NULL,
  `institute_fee` decimal(10,2) DEFAULT NULL,
  `fee_receipt_data` varchar(50) DEFAULT NULL,
  `reserve_cat` varchar(20) DEFAULT NULL,
  `physically_challenged` varchar(10) DEFAULT NULL,
  `income` decimal(10,2) DEFAULT NULL,
  `previous_college` varchar(200) DEFAULT NULL,
  `prev_college_place` varchar(100) DEFAULT NULL,
  `urban_rural` varchar(10) DEFAULT NULL,
  `aadhar_no` varchar(30) DEFAULT NULL,
  `blood_group` varchar(20) DEFAULT NULL,
  `bank_account` varchar(30) DEFAULT NULL,
  `bank_address` varchar(500) DEFAULT NULL,
  `email_id` varchar(100) DEFAULT NULL,
  `how_gmit` varchar(100) DEFAULT NULL,
  `address` varchar(500) NOT NULL,
  `district` varchar(100) NOT NULL,
  `taluk` varchar(100) NOT NULL,
  `state` varchar(50) NOT NULL,
  `submitted_documents` text NOT NULL,
  `pending_documents` text NOT NULL,
  `schedule_1` decimal(10,2) NOT NULL,
  `schedule_1_date` date NOT NULL,
  `schedule_2` decimal(10,2) NOT NULL,
  `schedule_2_date` date NOT NULL,
  `schedule_3` decimal(10,2) NOT NULL,
  `schedule_3_date` date NOT NULL,
  `schedule_4` decimal(10,2) NOT NULL,
  `schedule_4_date` date NOT NULL,
  `remarks` varchar(500) NOT NULL,
  `photo` text DEFAULT NULL,
  `attachments` longtext NOT NULL,
  `comments` text NOT NULL,
  `hostel` varchar(5) NOT NULL,
  `pickup_point` varchar(100) NOT NULL,
  `cob` int(11) NOT NULL DEFAULT 0,
  `coq` int(11) NOT NULL DEFAULT 0,
  `status` int(11) NOT NULL DEFAULT 1 COMMENT '1-ADMITTED 0-CANCELLED',
  `LAST_UPDATED` datetime NOT NULL DEFAULT current_timestamp(),
  
  PRIMARY KEY (`SL_NO`),
  UNIQUE KEY `usn` (`usn`) USING BTREE,
  KEY `idx_aadhar` (`aadhar`),
  KEY `idx_usn_aadhar` (`usn`, `aadhar`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- ============================================
-- VERIFICATION
-- ============================================
-- Check if table was created successfully
SELECT 'ad_student_details table created/verified successfully' as status;
